import { Template } from '@/types/template'

export const TEMPLATES: Template[] = [
  {
    id: 'dreamland',
    name: 'Dreamland Adventure',
    description: 'A magical journey through dreams',
    icon: 'moon.stars.fill',
    glyph: '\u263E',
    gradientStartLight: '#E8E5FF',
    gradientEndLight: '#B8ABE8',
    gradientStartDark: '#2E2B4A',
    gradientEndDark: '#3B3458',
    fields: [{ id: 'favoriteColor', label: 'Favorite Color', type: 'color' }],
  },
  {
    id: 'animal-friends',
    name: 'Animal Friends',
    description: 'Befriend animals in a whispering forest',
    icon: 'hare.fill',
    glyph: '\u2740',
    gradientStartLight: '#FBE1CC',
    gradientEndLight: '#F4C7A0',
    gradientStartDark: '#3A2E28',
    gradientEndDark: '#4E3D32',
    fields: [{ id: 'favoriteAnimal', label: 'Favorite Animal', type: 'animal' }],
  },
  {
    id: 'under-the-stars',
    name: 'Under the Stars',
    description: 'Explore the peaceful night sky',
    icon: 'sparkles',
    glyph: '\u2726',
    gradientStartLight: '#DCD5F1',
    gradientEndLight: '#B8ABE8',
    gradientStartDark: '#2A254A',
    gradientEndDark: '#3B3458',
    fields: [{ id: 'favoriteThing', label: 'Favorite Thing', type: 'text' }],
  },
  {
    id: 'underwater-journey',
    name: 'Underwater Journey',
    description: 'Drift through a gentle ocean world',
    icon: 'water.waves',
    glyph: '\u223C',
    gradientStartLight: '#D4E4F0',
    gradientEndLight: '#B9D0E5',
    gradientStartDark: '#1E2E3A',
    gradientEndDark: '#2E3E4A',
    fields: [{ id: 'favoriteColor', label: 'Favorite Color', type: 'color' }],
  },
  {
    id: 'space-explorer',
    name: 'Space Explorer',
    description: 'A slow, peaceful trip through the cosmos',
    icon: 'moonphase.waning.crescent',
    glyph: '\u272A',
    gradientStartLight: '#DCD5F1',
    gradientEndLight: '#B8ABE8',
    gradientStartDark: '#2A254A',
    gradientEndDark: '#3F3A5C',
    fields: [{ id: 'favoriteThing', label: 'Favorite Thing', type: 'text' }],
  },
  {
    id: 'fairy-garden',
    name: 'Fairy Garden',
    description: 'Wander through a tiny magical garden',
    icon: 'leaf',
    glyph: '\u273F',
    gradientStartLight: '#F6DCE1',
    gradientEndLight: '#E9B5C1',
    gradientStartDark: '#3A1E2E',
    gradientEndDark: '#4C2E3C',
    fields: [{ id: 'favoriteColor', label: 'Favorite Color', type: 'color' }],
  },
  {
    id: 'snowy-mountain',
    name: 'Snowy Mountain',
    description: 'A cozy adventure in gentle snowfall',
    icon: 'snow',
    glyph: '\u2744',
    gradientStartLight: '#E4ECEE',
    gradientEndLight: '#B8C8CC',
    gradientStartDark: '#1E2E34',
    gradientEndDark: '#30404A',
    fields: [{ id: 'favoriteAnimal', label: 'Favorite Animal', type: 'animal' }],
  },
  {
    id: 'rainy-day-cozy',
    name: 'Rainy Day Cozy',
    description: 'Curl up and listen to the rain',
    icon: 'rainy',
    glyph: '\u2042',
    gradientStartLight: '#D4DEE8',
    gradientEndLight: '#A8BBCE',
    gradientStartDark: '#202838',
    gradientEndDark: '#30394A',
    fields: [{ id: 'favoriteThing', label: 'Favorite Thing', type: 'text' }],
  },
]
