import { Template } from '@/types/template'

export const TEMPLATES: Template[] = [
  {
    id: 'dreamland',
    name: 'Dreamland Adventure',
    description: 'A magical journey through dreams',
    icon: 'moon.stars.fill',
    cardColorLight: '#E8E5FF',
    cardColorDark: '#2E2B4A',
    fields: [{ id: 'favoriteColor', label: 'Favorite Color', type: 'color' }],
  },
  {
    id: 'animal-friends',
    name: 'Animal Friends',
    description: 'Befriend animals in a whispering forest',
    icon: 'hare.fill',
    cardColorLight: '#FFE8D6',
    cardColorDark: '#3A2E28',
    fields: [{ id: 'favoriteAnimal', label: 'Favorite Animal', type: 'animal' }],
  },
  {
    id: 'under-the-stars',
    name: 'Under the Stars',
    description: 'Explore the peaceful night sky',
    icon: 'sparkles',
    cardColorLight: '#D4F0E7',
    cardColorDark: '#1E3A30',
    fields: [{ id: 'favoriteThing', label: 'Favorite Thing', type: 'text' }],
  },
  {
    id: 'underwater-journey',
    name: 'Underwater Journey',
    description: 'Drift through a gentle ocean world',
    icon: 'water.waves',
    cardColorLight: '#D6ECFF',
    cardColorDark: '#1E2E3A',
    fields: [{ id: 'favoriteColor', label: 'Favorite Color', type: 'color' }],
  },
  {
    id: 'space-explorer',
    name: 'Space Explorer',
    description: 'A slow, peaceful trip through the cosmos',
    icon: 'moonphase.waning.crescent',
    cardColorLight: '#E5DFFF',
    cardColorDark: '#2A254A',
    fields: [{ id: 'favoriteThing', label: 'Favorite Thing', type: 'text' }],
  },
  {
    id: 'fairy-garden',
    name: 'Fairy Garden',
    description: 'Wander through a tiny magical garden',
    icon: 'leaf',
    cardColorLight: '#FFE0EC',
    cardColorDark: '#3A1E2E',
    fields: [{ id: 'favoriteColor', label: 'Favorite Color', type: 'color' }],
  },
  {
    id: 'snowy-mountain',
    name: 'Snowy Mountain',
    description: 'A cozy adventure in gentle snowfall',
    icon: 'snow',
    cardColorLight: '#E8F4F8',
    cardColorDark: '#1E2E34',
    fields: [{ id: 'favoriteAnimal', label: 'Favorite Animal', type: 'animal' }],
  },
  {
    id: 'rainy-day-cozy',
    name: 'Rainy Day Cozy',
    description: 'Curl up and listen to the rain',
    icon: 'rainy',
    cardColorLight: '#DAE8F0',
    cardColorDark: '#202838',
    fields: [{ id: 'favoriteThing', label: 'Favorite Thing', type: 'text' }],
  },
]
